### ISSUE TITLE
merge text from section 4.4 to Section 4.2, with proposed text (revision -13)

### ISSUE THREAD

**Issue by ShuaiZhao** [ietf-wg-drip/draft-ietf-drip-arch#31]
From Stu:

-arch Section 4.4

should be merged wih Section 4.2

```HHIT for DRIP Identifier Cryptographic
The only (known to the authors of this document at the time of its
writing) extant fixed-length ID cryptographically derived from a
public key are the Host Identity Tag [RFC7401], HITs, and
Cryptographically Generated Addresses [RFC3972], CGAs.  However, both
HITs and CGAs lack registration/retrieval capability.  HHIT, on the
other hand, is capable of providing a cryptographic hashing function,
along with a registration process to mitigate the probability of a
hash collision (first registered, first allowed).
```

TO 

```
HHIT as a Cryptographic Identifier
The only (known to the authors at the time of this writing) extant
types of IP address compatible identifiers cryptographically derived
from the public keys of the identified entities are Cryptographically
Generated Addresses (CGAs) [RFC3972] and Host Identity Tags (HITs)
[RFC7401].  CGAs and HITs lack registration/retrieval capability.
To provide this, each HHIT embeds plaintext information designating
the hierarchy within which it is registered and a cryptographic hash
of that information concatenated with the entity's public key, etc.
Although hash collisions may occur, the registrar can detect them
and reject registration requests rather than issue credentials, e.g.,
by enforcing a first-claimed, first-attested policy.```

**Comment by mglt** [comment]
I suspect that the current section repeats a lot of information mention into section 4.2. -- assuming that self attestation has already been explained. Overall my comment is that 4.2 needs to be rewritten as a whole to ensure coherence and avoid different part of the text to repeat themselves. 

HHIT as a Cryptographic Identifier
The only (known to the authors at the time of this writing) extant
types of IP address compatible identifiers cryptographically derived
from the public keys of the identified entities are Cryptographically
Generated Addresses (CGAs) [RFC3972] and Host Identity Tags (HITs)
[RFC7401].  CGAs and HITs lack registration/retrieval capability.

information above does not seem to me useful to the arch. 

To provide this, each HHIT embeds plaintext information designating
the hierarchy within which it is registered. This ensures uniqueness of the RID as hash collision will be detected and managed (rejected) by the registrar. 

The above seems to me the only important information 

 and a cryptographic hash
of that information concatenated with the entity's public key, etc.
Although hash collisions may occur, the registrar can detect them
and reject registration requests rather than issue credentials, e.g.,
by enforcing a first-claimed, first-attested policy.```

**Comment by ShuaiZhao** [comment]
```
4.2.  HIT as A Trustworthy DRIP Entity Identifier

      Editor-note 15: general comments about rewrite of this section due
      to lack of coherence.
```

**Comment by ShuaiZhao** [comment]
rewrite/reorganized section 4.1,4.2,4.3 in -15
